### ISSUE TITLE
Typo in the expose-metafields method

### ISSUE THREAD

**Issue by 8geonirt** [getnacelle/nacelle-react#27]
## Issue summary
I am trying to use the `react-recharge` package, I was following the instructions described here: https://github.com/getnacelle/nacelle-react/tree/main/packages/react-recharge

When I executed this command `npx expose-metafields` I got an error

## Expected behavior

After running `npx expose-metafields` we should see the following output:
![image](https://user-images.githubusercontent.com/2782816/104652045-2a458800-567e-11eb-9ed4-a4f7e0ca88fa.png)

## Actual behavior
When running `npx expose-metafields` the following error appears

![image](https://user-images.githubusercontent.com/2782816/104651447-498fe580-567d-11eb-97d7-067e27a04e14.png)

The error is happening here: `node_modules/@nacelle/react-recharge/scripts/expose-metafields.js:47:13)`

I started debugging to see what the actual error is and I realized the error message is this one:
![image](https://user-images.githubusercontent.com/2782816/104651589-780dc080-567d-11eb-9974-7eb57c5cf575.png)

After doing more debugging I noticed there's a typo in line 62 => `({ node }) => node.namespace === 'subscription'`

```
function validateMetafields(requiredFields, exposedMetafields) {
  const subscriptions = exposedMetafields.filter(
    ({ node }) => node.namespace === 'subscription'
  );
...
```
It should be `subscriptions` instead of `subscription`.

The `interphase-node` module is expecting the metafields namespace to be `subscriptions`:

![image](https://user-images.githubusercontent.com/2782816/104651890-e9e60a00-567d-11eb-8e9e-0025ad3ad56d.png)
_Code from the `interphase-node` package._

## Reduced test case

We only need to add an `s` 

## Specifications

```bash
  System:
    OS: Linux 4.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 15.58 GB / 31.88 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.19.1 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
```

**I could add a PR for this, let me know if you are open to this.**

**Comment by NWRichmond** [comment]
Hi @8geonirt! Good catch. We would be happy to review a PR for this.

**Comment by 8geonirt** [comment]
@NWRichmond thanks for replying so quickly, I'd be happy to contribute, is it possible to allow forking the project so I can point my PR to this repository?

**Comment by 8geonirt** [comment]
Thanks for reviewing my PR, now this issue can be closed 🤓
