### ISSUE TITLE
Issue With NextJs Redering

### ISSUE THREAD

**Issue by sajumani** [getnacelle/nacelle-react#31]
Intial Load page it's working, after navgating to some other page.  form Id resets to undefined

**Comment by NWRichmond** [comment]
Hi @sajumani! Which Form ID are you referring to? Is this for the https://github.com/getnacelle/nacelle-react/tree/main/examples/withKlaviyo project?

**Comment by sajumani** [comment]
Thanks for quick reply;

KLAVIYO_COMPANY_ID=Uvqr4q
KLAVIYO_FORM_EMBED_CODE=YteX3P

Yes am integrating with same model

**Comment by sajumani** [comment]
@NWRichmond Script i added in _Document
Form i added in footer component

**Comment by sajumani** [comment]
@NWRichmond Any idea?

**Comment by NWRichmond** [comment]
@sajumani I think in order to proceed with investigating this, we would need to see a demonstration of this issue with a minimal reproduction example. Could you please provide a link to a [CodeSandbox](https://codesandbox.io/) or similar?

**Comment by NWRichmond** [comment]
Closing this for now, but would be open to reopening if provided a minimal reproduction example.
