### ISSUE TITLE
[examples/gatsby] Why does the Gatsby example project require two sets of Nacelle space credentials?

### ISSUE THREAD

**Issue by hotcakedev628** [getnacelle/nacelle-react#38]
I am getting three errors while running `npm run develop`.

One of them is getting an error with `gatsby-plugin-image` especially using `gatsbyImageData` about `Layout: FLUID`.
```
          featuredMedia {
            remoteImage {
              childImageSharp {
                gatsbyImageData(maxWidth: 320, layout: FLUID)
              }
            }
            src
            altText
          }
```
(It seems it has fixed now, right?)
https://github.com/getnacelle/nacelle-react/blob/0ec938110b5a886766da29357e930456031dc5d1/examples/gatsby/src/templates/collection.js#L31

And another one is getting an error with Nacelle service function in the codebase.
https://github.com/getnacelle/nacelle-react/blob/0ec938110b5a886766da29357e930456031dc5d1/examples/gatsby/src/services/nacelle.js#L4

It seems it has fixed as well by adding prefix `GATSBY_` to env variables.

```
import NacelleClient from '@nacelle/client-js-sdk';

const settings = {
  id: process.env.GATSBY_NACELLE_SPACE_ID,
  token: process.env.GATSBY_NACELLE_GRAPHQL_TOKEN,
  nacelleEndpoint: 'https://hailfrequency.com/v2/graphql',
  useStatic: false
};

const $nacelle = new NacelleClient(settings);

export default $nacelle;
```

But I am still curious.
Why the variables `GATSBY_NACELLE_SPACE_ID` and `GATSBY_NACELLE_GRAPHQL_TOKEN` are using another variables because they are the same as `NACELLE_SPACE_ID` and `NACELLE_GRAPHQL_TOKEN` in `gatsby-config.js`, right?
We have the same variables(server-side), but also they have the same variables in client-side?
What if we integrate them as `GATSBY_NACELLE_SPACE_ID` and `GATSBY_NACELLE_GRAPHQL_TOKEN`?

And the last error is what I am getting from rendering GraphQL queries while I am building the project.
```
npm run build
```

The error seems to be getting from Shopify products, right?
https://github.com/getnacelle/nacelle-react/blob/0ec938110b5a886766da29357e930456031dc5d1/examples/gatsby/src/components/ProductCard/ProductCard.js#L63

![image](https://user-images.githubusercontent.com/60177750/112502072-227e2000-8d60-11eb-875c-78aecf65b7ad.png)
Maybe, the product was having an issue?

**Comment by NWRichmond** [comment]
Hi @hotcakedev628, I've just created a ticket for us to update the Gatsby example. One of the updates will involve removing the Nacelle client entirely, since it's really not needed - all of the data fetching can happen via Gatsby's internal query engine.

We'll wait to close this issue until an accompanying PR is merged.

With respect to:
> The error seems to be getting from Shopify products, right?

This seems like an issue that would best be handled via the [Nacelle Service Desk](https://nacelle.atlassian.net/servicedesk/customer/portal/7). If you could please let us know in your support request which merchant project this works relates to, that would be very helpful.

**Comment by hotcakedev628** [comment]
Hi @NWRichmond .
Thank you for answering to my questions.

> The error seems to be getting from Shopify products, right?

Regarding that issue, some products were having `product.featuredMedia` `null`.
So I was able to fix that to
```
const altText =
    product.featuredMedia
      ? product.featuredMedia.altText
      : product.title
        ? product.title
        : 'product card';
```
And also 
```
              <Image
                src={product.featuredMedia
                  ? product.featuredMedia.src
                  : defaultProductImage
                }
                alt={altText}
                width={320}
                format={IMAGE_FORMATS}
                styles={imageStyles}
              />
```
Thank you!
I am happy to use `Nacelle` for headless eCommerce.

**Comment by NWRichmond** [comment]
Excellent! I like the way you're handling falsey `product.featuredMedia`.
